substitutions:
    _REPO: mp-boilerplate-api
steps:
- name: ubuntu
  args: [ 'bash', '-c', 'test $(echo ${REPO_NAME}|grep -o ${_REPO}|wc -l) -eq 1 && echo "match" || exit 1' ]

- name: gcr.io/kaniko-project/executor:v0.16.0
  args:
  - --destination=gcr.io/$PROJECT_ID/$_REPO:${COMMIT_SHA}
  - --destination=gcr.io/$PROJECT_ID/$_REPO:${BRANCH_NAME}
  - --destination=gcr.io/$PROJECT_ID/$_REPO:${TAG_NAME}
  - --cache=true
  - --cache-ttl=6h
