name: Gitrack Shield Action

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITRACK_SECRET: ${{ secrets.SECURITY_GLOBAL_ACCESS_TOKEN }}
      GITHUB_CX: ${{ toJson(github) }}

    steps:
    - uses: actions/checkout@master
    - name: Setup Gitrack Shield
      id: setup-gitrack
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/gitrack-shield/scripts/gitrack-setup.sh | sh -
    - name: Running Gitrack Shield (Secrets Scanning)
      id: running-gitrack
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/gitrack-shield/scripts/gitrack-shield-scan.sh | sh -
    - name: Repository Cleanup Process
      id: repo-cleanup
      continue-on-error: true
      if: ${{ failure() && github.event_name == 'pull_request' && github.event.action == 'opened' }}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/gitrack-shield/scripts/gitrack-cleanup-process.sh | sh -
    - name: Safety Checks
      id: safety-checks
      continue-on-error: true
      if: ${{ failure() && github.event.pull_request.merged == true && github.event_name == 'pull_request' && github.event.action == 'closed'}}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/gitrack-shield/scripts/gitrack-safety-check.sh | sh -
    - name: Security Reporting and Monitoring
      id: reporting-monitoring
      continue-on-error: true
      if: ${{ failure() }}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/gitrack-shield/scripts/gitrack-reporting-monitoring.sh | sh -