name: Vulnerability Scanner

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:

  results:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:     
      GITRACK_SECRET: ${{ secrets.SECURITY_GLOBAL_ACCESS_TOKEN }}
      SEC_REPORTS: ${{secrets.SEC_REPORTS}}
      GITHUB_CX: ${{ toJson(github) }}

    steps:
    - uses: actions/checkout@master
    
    - name: Setup VulnerabilityScanner  
      id: setup-vulnerability-scanner
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/setup.bash | bash -
    
    - name: cache requirements 
      id: cache-step
      uses: actions/cache@v2
      with:
        path: /opt/venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Requirements
      id: install-requirements
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/install-requirements.bash | bash -
        
    - name: Run VulnerabilityScanner 
      id: run-vulnerability-scanner
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/run.bash | bash - 
    
    - name: Printing The New EndPoints
      id: print-new-endpoints
      run: | 
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/print-new-endpoints.bash | bash - 
        
    - name: Printing All Of The Results
      id: print-all-results
      run: | 
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/print-all-results.bash | bash - 
    
    - name: Failure Monitoring and Reporting
      id: reporting-monitoring
      continue-on-error: true
      if: ${{ failure() }}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/report-failure.bash | bash -
    - name: Sending Notification to Teams
      id: send-notification-to-teams
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-secops-8a473ab3b5/vulnerability-scanner/scripts/send-notification-teams.bash | bash - 
        